global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIA4RMNVCTIM6VTK4P5
        secret_key: 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
        port: 9100
