global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.31.36.153:9090','172.31.34.108:9100','172.31.42.26:9100']

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
